create table if not exists public.mobile_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  event_properties jsonb not null default '{}'::jsonb,
  event_source text not null default 'mobile_app',
  session_id text,
  platform text,
  app_version text,
  build_number text,
  occurred_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  constraint mobile_analytics_events_event_name_length check (
    char_length(event_name) >= 1 and char_length(event_name) <= 120
  ),
  constraint mobile_analytics_events_event_source_check check (
    event_source in ('mobile_app')
  )
);

create index if not exists mobile_analytics_events_user_idx
on public.mobile_analytics_events(user_id, occurred_at desc);

create index if not exists mobile_analytics_events_name_idx
on public.mobile_analytics_events(event_name, occurred_at desc);

alter table public.mobile_analytics_events enable row level security;

drop policy if exists mobile_analytics_events_select_own on public.mobile_analytics_events;
create policy mobile_analytics_events_select_own
on public.mobile_analytics_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists mobile_analytics_events_insert_none_authenticated on public.mobile_analytics_events;
create policy mobile_analytics_events_insert_none_authenticated
on public.mobile_analytics_events
for insert
to authenticated
with check (false);

drop policy if exists mobile_analytics_events_insert_none_anon on public.mobile_analytics_events;
create policy mobile_analytics_events_insert_none_anon
on public.mobile_analytics_events
for insert
to anon
with check (false);

drop policy if exists mobile_analytics_events_update_none on public.mobile_analytics_events;
create policy mobile_analytics_events_update_none
on public.mobile_analytics_events
for update
to authenticated
using (false)
with check (false);

drop policy if exists mobile_analytics_events_delete_none on public.mobile_analytics_events;
create policy mobile_analytics_events_delete_none
on public.mobile_analytics_events
for delete
to authenticated
using (false);

create or replace function public.track_mobile_analytics_event(
  p_event_name text,
  p_event_properties jsonb default '{}'::jsonb,
  p_event_source text default 'mobile_app',
  p_session_id text default null,
  p_platform text default null,
  p_app_version text default null,
  p_build_number text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id bigint;
  v_event_name text := lower(btrim(coalesce(p_event_name, '')));
  v_event_properties jsonb := coalesce(p_event_properties, '{}'::jsonb);
  v_event_source text := coalesce(nullif(btrim(p_event_source), ''), 'mobile_app');
begin
  if v_event_name = '' then
    raise exception 'Event name is required.';
  end if;

  if char_length(v_event_name) > 120 then
    raise exception 'Event name exceeds max length.';
  end if;

  if v_event_name !~ '^[a-z0-9_]+$' then
    raise exception 'Event name contains unsupported characters.';
  end if;

  if jsonb_typeof(v_event_properties) is distinct from 'object' then
    raise exception 'Event properties must be a JSON object.';
  end if;

  if pg_column_size(v_event_properties) > 8192 then
    raise exception 'Event properties payload exceeds max size.';
  end if;

  insert into public.mobile_analytics_events (
    user_id,
    event_name,
    event_properties,
    event_source,
    session_id,
    platform,
    app_version,
    build_number
  )
  values (
    auth.uid(),
    v_event_name,
    v_event_properties,
    v_event_source,
    nullif(btrim(p_session_id), ''),
    nullif(btrim(p_platform), ''),
    nullif(btrim(p_app_version), ''),
    nullif(btrim(p_build_number), '')
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke all on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) from public;

revoke execute on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) from anon;
revoke execute on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) from authenticated;

grant execute on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) to anon;
grant execute on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) to authenticated;
grant execute on function public.track_mobile_analytics_event(
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) to service_role;
